version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/clojure:tools-deps-node
  environment:
    JVM_OPTS: -Xmx3200m

jobs:
  test-cli:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          key: project

      - run: npm install --prefix cli

      - save_cache:
          paths:
            - ~/.m2
            - ~/cli/node_modules
          key: project

      - run:
          name: Test CLI
          command: |
            cd cli
            npx shadow-cljs release test
            node build-test/clake-tests.js

  build-cli:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          key: project

      - run: npm install --prefix cli

      - run:
          name: Build CLI
          command: |
            cd cli
            ./scripts/release.sh

      - persist_to_workspace:
          root: cli
          paths:
            - build

  publish-cli:
    <<: *defaults

    steps:
      - checkout
      - attach_workspace:
          at: scripts

      - run:
          name: Move clake.js to build dir
          command: |
            mkdir cli/build
            mv scripts/build/clake.js cli/build/clake.js

      - run:
          name: Configure Git
          command: |
            git config --global user.email "compute-ci@computesoftware.com"
            git config --global user.name "compute-ci"

      - run:
          name: Configure NPM
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      - run:
          name: Bump version, commit, and create tag
          command: |
            cd cli
            export NEW_VERSION=$(npm version patch)
            cd ..
            git add .
            git commit -m "$NEW_VERSION" -m "[ci skip]"
            git tag -a $NEW_VERSION -m ""
      - run:
          name: NPM publish
          command: |
            cd cli
            npm publish
      - run:
          name: Push commits and tags
          command: |
            git push
            git push --tags

  test-jvm-code:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: scripts
      # TODO: This needs to be replaced with a real install task in npm
      - run:
          name: Install Clake
          command: |
            cd scripts/build
            chmod +x clake.js
            sudo mv clake.js /usr/local/bin/clake
      - run:
          name: Test common
          command: |
            cd common
            clake -A :test test

workflows:
  version: 2
  ci-workflow:
    jobs:
      - test-cli:
          context: clojure-env
      - build-cli:
          context: clojure-env
      - publish-cli:
          requires:
            - test-cli
            - build-cli
            - test-tasks
          filters:
            branches:
              only:
                - master
      - test-jvm-code:
          context: clojure-env
          requires:
            - test-cli
            - build-cli