version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/clojure:tools-deps-node
  environment:
    JVM_OPTS: -Xmx3200m

jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/clojure:lein-2.8.1-node

    steps:
      - checkout

      - restore_cache:
          key: project

      - run: npm install --prefix cli
      - run: |
          cd cli
          ./scripts/release.sh

      - save_cache:
          paths:
            - ~/.m2
            - ~/cli/node_modules
          key: project
      - persist_to_workspace:
          root: cli
          paths:
            - build/*

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: scripts
      - run: |
        cd tasks
        node ./scripts/build2/clake.js test


workflows:
  version: 2
  ci-workflow:
    jobs:
      - build:
          context: clojure-env
      - test:
          context: clojure-env
          requires:
            - build