version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/clojure:tools-deps-node
  environment:
    JVM_OPTS: -Xmx3200m

jobs:
  test-cli:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          key: project

      - run: npm install --prefix cli

      - save_cache:
          paths:
            - ~/.m2
            - ~/cli/node_modules
          key: project

      - run:
          name: Test CLI
          command: |
            cd cli
            npx shadow-cljs release test

  build-cli:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          key: project

      - run: npm install --prefix cli

      - run:
          name: Build CLI
          command: |
            cd cli
            ./scripts/release.sh

      - persist_to_workspace:
          root: cli
          paths:
            - build

  publish-cli:
    <<: *defaults

    steps:
      - checkout
      - attach_workspace:
          at: scripts
      - run:
          name: Move clake.js to build dir
          command: |
            mkdir cli/build
            mv scripts/build/clake.js cli/build/clake.js

      - run:
          name: Bump version, commit, and create tag
          command: |
            export NEW_VERSION=$(npm version patch)
            git add package.json package-lock.json
            git commit -m "$NEW_VERSION"
            git tag -a $NEW_VERSION -m ""
            git push
      - run: npm publish

  test-tasks:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: scripts
      # TODO: This needs to be replaced with a real install task in npm
      - run:
          name: Install Clake
          command: |
            cd scripts/build
            chmod +x clake.js
            sudo mv clake.js /usr/local/bin/clake
      - run:
          name: Run tests
          command: |
            cd tasks
            clake test


workflows:
  version: 2
  ci-workflow:
    jobs:
      - test-cli:
          context: clojure-env
      - build-cli:
          context: clojure-env
      - publish-cli:
          requires:
            - test-cli
            - build-cli
            - test-tasks
          filters:
            branches:
              only:
                - master
      - test-tasks:
          context: clojure-env
          requires:
            - test-cli
            - build-cli