version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/clojure:tools-deps-node
  environment:
    JVM_OPTS: -Xmx3200m

jobs:
  test-cli:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          key: project

      - run: npm install --prefix cli

      - save_cache:
          paths:
            - ~/.m2
            - ~/cli/node_modules
          key: project

      - run:
          name: Test CLI
          command: |
            cd cli
            npx shadow-cljs release test

  build-cli:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          key: project

      - run: npm install --prefix cli

      - run:
          name: Build CLI
          command: |
            cd cli
            ./scripts/release.sh

      - persist_to_workspace:
          root: cli
          paths:
            - build

  test-tasks:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: scripts
      - run: |
          cd tasks
          node ./scripts/build/clake.js test


workflows:
  version: 2
  ci-workflow:
    jobs:
      - test-cli:
          context: clojure-env
      - build-cli:
          context: clojure-env
      - test-tasks:
          context: clojure-env
          requires:
            - build-cli